"""
Django settings for CBT project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

TIME_ZONE = 'Africa/Lagos'
USE_TZ = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a##=*=svs=^z1&+e_#ihbxzvo(0429u%cts$5)a2*epz!)y2h#'
YOUTUBE_API_KEY = 'AIzaSyDwrfseaiXFHU9cmyVGxlNkqKep9ZBdp88'
TERMIL_API_KEY = "TLRbUaGTsMAiAKQMZxYOSHlOIFAeqbglGDPnPWExMvZEgNnoKSQNIeMkjNttiD"
HF_TOKEN_API = "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"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True          # ✅ Use TLS
EMAIL_USE_SSL = False         # ❌ Don't use SSL when using TLS
EMAIL_HOST_USER = 'wonderpaul243@gmail.com' 
EMAIL_HOST_PASSWORD = 'cxuzngiwllihmayb'  # App password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

JAZZMIN_SETTINGS = {
    "site_title": "Heroes School Admin",
    "site_header": "Heroes School Admin Developments",
    "site_brand": "Heroes Schools",
    "welcome_sign": "Welcome to Heroes Schools Admin",
    "copyright": "Heroes 2025",
    "show_sidebar": True,
    "navigation_expanded": True,
    "user_avatar": None,
    "theme": "cosmo"
}

# JAZZMIN_UI_TWEAKS = {
#     "theme": "cyborg",  # available: "default", "cerulean", "cosmo", "cyborg", "darkly",
#                         # "flatly", "journal", "litera", "lumen", "lux", "materia",
#                         # "minty", "pulse", "sandstone", "simplex", "sketchy",
#                         # "slate", "solar", "spacelab", "superhero", "united", "yeti"

#     "navbar": "navbar-dark navbar-primary",
#     "sidebar": "sidebar-dark-primary",
#     "brand_colour": "navbar-primary",
#     "accent": "accent-white",
# }


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    "django_browser_reload",
    'widget_tweaks',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'myapp.exam.middleware.ExamLockMiddleware',
]

ROOT_URLCONF = 'CBT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CBT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'heroeyjb_heroes',
        'USER': 'root',
        'PASSWORD': '',          # leave blank if no password
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  'static'),
]

STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR,  'media')

MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
