# Generated by Django 4.2.23 on 2025-10-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.CharField(max_length=50, verbose_name='About Us')),
                ('mission', models.CharField(max_length=100, verbose_name='Mission')),
                ('vision', models.CharField(max_length=100, verbose_name='Vision')),
                ('aboutImage', models.FileField(upload_to='aboutImage/')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Class / Level Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class / Level',
                'verbose_name_plural': 'Classes / Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Course / Subject Title')),
                ('code', models.CharField(max_length=20, verbose_name='Course / Subject Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('credit_unit', models.PositiveIntegerField(default=1, help_text='Can represent credit units (University) or subject weight (Secondary)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('classgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.classgroup', verbose_name='Class / Level')),
            ],
            options={
                'verbose_name': 'Course / Subject',
                'verbose_name_plural': 'Courses / Subjects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('Secondary', 'Secondary School'), ('College', 'College'), ('Polytechnic', 'Polytechnic'), ('University', 'University'), ('Other', 'Other Institution')], default='Secondary', max_length=20, verbose_name='Institution Type')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department / Class Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department / Class',
                'verbose_name_plural': 'Departments / Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schoollogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoText', models.TextField(max_length=50, verbose_name='Logo Text')),
                ('LogoImage', models.FileField(upload_to='logo_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Admission / Matric No.')),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent / Guardian Name')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parent / Guardian Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='myapp.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.department')),
                ('level_or_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classgroup', verbose_name='Class / Level ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student / Learner',
                'verbose_name_plural': 'Students / Learners',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
                ('test_type', models.CharField(choices=[('1st Test', '1st Test'), ('2nd Test', '2nd Test'), ('3rd Test', '3rd Test')], max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('class_groups', models.ManyToManyField(blank=True, related_name='teachers', to='myapp.classgroup', verbose_name='Classes / Levels')),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='myapp.course', verbose_name='Courses / Subjects')),
                ('department', models.ManyToManyField(blank=True, related_name='teachers', to='myapp.department', verbose_name='Departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher / Lecturer',
                'verbose_name_plural': 'Teachers / Lecturers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Fourth Term', 'Fourth Term'), ('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Third Semester', 'Third Semester')], max_length=50, verbose_name='Term / Semester')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Fourth Term', 'Fourth Term'), ('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Third Semester', 'Third Semester')], max_length=50, verbose_name='Term / Semester')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classgroup')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exam')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.department'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='myapp.department'),
        ),
        migrations.CreateModel(
            name='MarkedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('total_score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_exams', to='myapp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_exams', to='myapp.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('department', 'name')},
        ),
    ]
