# Generated by Django 4.2.23 on 2025-10-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_resultaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='phonNo',
            field=models.CharField(default=1, max_length=50, verbose_name='Phone No'),
            preserve_default=False,
        ),
    ]
