# Generated by Django 4.2.23 on 2025-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_title_address_title_email_title_phonno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregatedPercentahe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorePercent', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
