# Generated by Django 4.2.23 on 2025-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_agregatedpercentahe_alter_title_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregatedpercentahe',
            name='scorePercent',
            field=models.FloatField(help_text='Enter the percentage multiplier for calculating exam scores (e.g. 100 for 100%).', unique=True),
        ),
    ]
