# Generated by Django 4.2.23 on 2025-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_agregatedpercentahe_scorepercent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agregatedpercentahe',
            options={'verbose_name': 'Agregate Percentage'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='classgroup',
        ),
        migrations.AddField(
            model_name='course',
            name='classgroup',
            field=models.ManyToManyField(blank=True, related_name='courses', to='myapp.classgroup', verbose_name='Class / Level'),
        ),
    ]
