# Generated by Django 4.2.23 on 2025-11-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_agregatedpercentahe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='class_group',
            field=models.CharField(max_length=20),
        ),
    ]
