# Generated by Django 4.2.23 on 2025-11-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_testscore_class_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('AUDIO', 'Audio'), ('LINK', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='lectures/files/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=255)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='myapp.course')),
            ],
        ),
    ]
